export const GET_PRODUCTS_SUCESS = "GET_PRODUCTS_SUCESS";
export const GET_PRODUCTS_FALI = "GET_PRODUCTS_FALI";


export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const COUNT_INCREASE = "COUNT_INCREASE" ;
export const COUNT_DECREASE = "COUNT_DECREASE";